### ISSUE TITLE
OTP 2 - rest api throws exceptions with non-standard parameter values

### ISSUE THREAD

**Issue by fpurcell** [ibi-group/OpenTripPlanner#169]
TriMet still uses the rest api for a legacy 1.x test suite.  In some of these tests, the optimize=TRANSFERS (a valid value on OTP 1.x) is used, which results in OTP 2.x returning a 404 error as the request causes an exception.

## Expected behavior

OTP 2.x should return a valid response when a parameter value is in the request that OTP 2.x does not understand.  The response could be either an error with properly formatted json and message.  Or better yet, just use the default value for a given parameter, and return a trip response.

## Observed behavior

https://ipdrgehnn6.execute-api.us-east-1.amazonaws.com/dev/otp2/routers/default/plan?fromPlace=NW Flanders St%3A%3A45.52595%2C-122.680611956&toPlace=SW Market St%3A%3A45.51194091%2C-122.677007&optimize=TRANSFERS throws java exceptions and causes a 404 response from the rest api

## Version of OTP used (exact commit hash or JAR name)

version: 2.4.0-SNAPSHOT, commit: d64f319a8b5215651349953eb4f9450ad01b1bf1

## Router config and graph build config JSON

http://maps8.trimet.org/ct/router-config.json

## Steps to reproduce the problem

Start a local instance of OTP 2.x and then call https://localhost:8080/dev/otp2/routers/default/plan?fromPlace=NW Flanders St%3A%3A45.52595%2C-122.680611956&toPlace=SW Market St%3A%3A45.51194091%2C-122.677007&optimize=TRANSFERS

**Comment by fpurcell** [comment]
https://github.com/opentripplanner/OpenTripPlanner/issues/5196

**Comment by markstos** [comment]
I ran into a crash like this today when testing the traveltime/isochrone API. I triggered a null pointer exception on my first attempt to the use the API. I expect that no matter whether the API is REST of GraphQL that the inputs would be validated.

 'https://iexample.com/otp/traveltime/isochrone?location=39.168471624937,-86.51928558368158&mode=BICYCLE&cutoff=1800S'

```
 java.lang.IllegalStateException: Unable to perform operation: create on org.opentripplanner.ext.traveltime.TravelTimeResource
         at org.jvnet.hk2.internal.ClazzCreator.create(ClazzCreator.java:428)
         at org.jvnet.hk2.internal.SystemDescriptor.create(SystemDescriptor.java:466)
         at org.glassfish.jersey.inject.hk2.RequestContext.findOrCreate(RequestContext.java:59)
         at org.jvnet.hk2.internal.Utilities.createService(Utilities.java:2109)
         at org.jvnet.hk2.internal.ServiceLocatorImpl.internalGetService(ServiceLocatorImpl.java:769)
         at org.jvnet.hk2.internal.ServiceLocatorImpl.internalGetService(ServiceLocatorImpl.java:732)
         at org.jvnet.hk2.internal.ServiceLocatorImpl.getService(ServiceLocatorImpl.java:702)
         at org.glassfish.jersey.inject.hk2.AbstractHk2InjectionManager.getInstance(AbstractHk2InjectionManager.java:160)
         at org.glassfish.jersey.inject.hk2.ImmediateHk2InjectionManager.getInstance(ImmediateHk2InjectionManager.java:30)
         at org.glassfish.jersey.internal.inject.Injections.getOrCreate(Injections.java:122)
         at org.glassfish.jersey.server.model.MethodHandler$ClassBasedMethodHandler.getInstance(MethodHandler.java:260)
         at org.glassfish.jersey.server.internal.routing.PushMethodHandlerRouter.apply(PushMethodHandlerRouter.java:51)
         at org.glassfish.jersey.server.internal.routing.RoutingStage._apply(RoutingStage.java:86)
         at org.glassfish.jersey.server.internal.routing.RoutingStage._apply(RoutingStage.java:89)
         at org.glassfish.jersey.server.internal.routing.RoutingStage._apply(RoutingStage.java:89)
         at org.glassfish.jersey.server.internal.routing.RoutingStage._apply(RoutingStage.java:89)
         at org.glassfish.jersey.server.internal.routing.RoutingStage._apply(RoutingStage.java:89)
         at org.glassfish.jersey.server.internal.routing.RoutingStage.apply(RoutingStage.java:69)
         at org.glassfish.jersey.server.internal.routing.RoutingStage.apply(RoutingStage.java:38)
         at org.glassfish.jersey.process.internal.Stages.process(Stages.java:173)
         at org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:253)
         at org.glassfish.jersey.internal.Errors$1.call(Errors.java:248)
         at org.glassfish.jersey.internal.Errors$1.call(Errors.java:244)
         at org.glassfish.jersey.internal.Errors.process(Errors.java:292)
         at org.glassfish.jersey.internal.Errors.process(Errors.java:274)
         at org.glassfish.jersey.internal.Errors.process(Errors.java:244)
         at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:265)
         at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:240)
         at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:697)
         at org.glassfish.jersey.grizzly2.httpserver.GrizzlyHttpContainer.service(GrizzlyHttpContainer.java:367)
         at org.glassfish.grizzly.http.server.HttpHandler$1.run(HttpHandler.java:190)
         at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:535)
         at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:515)
         at java.base/java.lang.Thread.run(Unknown Source)
```
