### ISSUE TITLE
OTP fails to load certain GBFS feeds with extra fields

### ISSUE THREAD

**Issue by binh-dam-ibigroup** [ibi-group/OpenTripPlanner#60]
## Expected behavior

OTP should parse the following GBFS feeds without throwing an exception:
- https://gbfs.bcycle.com/bcycle_houston/gbfs.json
- https://gbfs.bcycle.com/bcycle_indego/gbfs.json

## Observed behavior

The feeds above contain extra fields `version`, `last_updated` that are not recognized by the JSON parser,
resulting in the following exception:

`Unrecognized field "version" (class org.opentripplanner.updater.vehicle_rental.GBFSMappings.GbfsResponse), not marked as ignorable`

Occurs on line: https://github.com/ibi-group/OpenTripPlanner/blob/3b44958c4ae60f67d4126c3a3b4678f90fa904a3/src/main/java/org/opentripplanner/updater/bike_rental/GbfsBikeRentalDataSource.java#L124

Example stack trace when polling the `/otp/routers/default/bike_rental` endpoint:
```log
17:19:49.514 ERROR (GbfsBikeRentalDataSource.java:94) [severity: FEED_WIDE] failed to deserialize gbfs.json response (network: GBFS)
17:19:49.522 ERROR (GenericJsonBikeRentalDataSource.java:97) [severity: ALL_STATIONS] Error reading bike rental feed from null (url: null)
java.net.MalformedURLException: null
	at java.net.URL.<init>(URL.java:644) ~[na:1.8.0_261]
	at java.net.URL.<init>(URL.java:507) ~[na:1.8.0_261]
	at java.net.URL.<init>(URL.java:456) ~[na:1.8.0_261]
	at org.opentripplanner.updater.bike_rental.GenericJsonBikeRentalDataSource.update(GenericJsonBikeRentalDataSource.java:106) ~[classes/:na]
	at org.opentripplanner.updater.bike_rental.GbfsBikeRentalDataSource.update(GbfsBikeRentalDataSource.java:67) [classes/:na]
	at org.opentripplanner.updater.bike_rental.BikeRentalUpdater.runPolling(BikeRentalUpdater.java:140) [classes/:na]
	at org.opentripplanner.updater.PollingGraphUpdater.run(PollingGraphUpdater.java:47) [classes/:na]
	at org.opentripplanner.updater.GraphUpdaterManager.lambda$startUpdaters$1(GraphUpdaterManager.java:162) [classes/:na]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[na:1.8.0_261]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[na:1.8.0_261]
	at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_261]
Caused by: java.lang.NullPointerException: null
	at java.net.URL.<init>(URL.java:549) ~[na:1.8.0_261]
	... 10 common frames omitted
17:19:49.523 ERROR (GenericJsonBikeRentalDataSource.java:97) [severity: ALL_FLOATING_VEHICLES] Error reading bike rental feed from null (url: null)
java.net.MalformedURLException: null
	at java.net.URL.<init>(URL.java:644) ~[na:1.8.0_261]
	at java.net.URL.<init>(URL.java:507) ~[na:1.8.0_261]
	at java.net.URL.<init>(URL.java:456) ~[na:1.8.0_261]
	at org.opentripplanner.updater.bike_rental.GenericJsonBikeRentalDataSource.update(GenericJsonBikeRentalDataSource.java:106) ~[classes/:na]
	at org.opentripplanner.updater.bike_rental.GbfsBikeRentalDataSource.update(GbfsBikeRentalDataSource.java:69) [classes/:na]
	at org.opentripplanner.updater.bike_rental.BikeRentalUpdater.runPolling(BikeRentalUpdater.java:140) [classes/:na]
	at org.opentripplanner.updater.PollingGraphUpdater.run(PollingGraphUpdater.java:47) [classes/:na]
	at org.opentripplanner.updater.GraphUpdaterManager.lambda$startUpdaters$1(GraphUpdaterManager.java:162) [classes/:na]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[na:1.8.0_261]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[na:1.8.0_261]
	at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_261]
Caused by: java.lang.NullPointerException: null
	at java.net.URL.<init>(URL.java:549) ~[na:1.8.0_261]
	... 10 common frames omitted
17:19:49.523 ERROR (GbfsBikeRentalDataSource.java:94) [severity: FEED_WIDE] Both station and vehicle info not found! (network: GBFS)

```

## Version of OTP used (exact commit hash or JAR name)

https://github.com/ibi-group/OpenTripPlanner/commit/95788c8c4b0c18065885ca7bd9af7e6c729e1bbf

## Data sets in use (links to GTFS and OSM PBF files)

- https://gbfs.bcycle.com/bcycle_houston/gbfs.json
- https://gbfs.bcycle.com/bcycle_indego/gbfs.json

## Command line used to start OTP

`--autoScan --server --port 8080 --basePath <path-to-otp-data>`

## Router config and graph build config JSON

```json
{
  // ... other configs...

  "updaters": [
    {
      "type": "bike-rental",
      "sourceType": "gbfs",
      "url": "https://gbfs.bcycle.com/bcycle_houston",
      "frequencySec": 30
    }

    // other updaters
  ]
}
```

## Steps to reproduce the problem

Query the `bike_rental` endpoint. An error message is returned and the exception appears in the terminal/logs.

**Comment by landonreed** [comment]
So @miles-grant-ibigroup, I'm guessing this is probably just a matter of adding Jackson ignore annotations to classes like: https://github.com/ibi-group/OpenTripPlanner/blob/ibi-dev/src/main/java/org/opentripplanner/updater/vehicle_rental/GBFSMappings/GbfsResponse.java.

I don't recall how familiar you are with Java, but feel free to reach out if you need any help getting OTP stuff set up!
